---
name: actionlint

on:
  pull_request:
    paths:
      - .github/workflows/*

jobs:
  actionlint:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1

      - name: Actionlint
        uses: reviewdog/action-actionlint@db58217885f9a6570da9c71be4e40ec33fe44a1f # v1.65.0
        with:
          level: error
          filter_mode: nofilter
