---
name: actionlint

on:
  pull_request:
    paths:
      - .github/workflows/*

jobs:
  actionlint:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Actionlint
        uses: reviewdog/action-actionlint@db58217885f9a6570da9c71be4e40ec33fe44a1f # v1.65.0
        with:
          level: error
          filter_mode: nofilter
